package com.restapi.repository;
import com.restapi.grpc.CourseGRPCAutoGenerated;
import com.restapi.grpc.CourseGRPCAutoGenerated.Course;
import com.restapi.grpc.CourseGRPCAutoGenerated.Courses;
import java.util.Iterator;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

public class CourseRepository {
	private static final Log log = LogFactory.getLog(CourseRepository.class);
	Map<Integer, Course> courses;
	public CourseRepository (Map<Integer, Course> courses) {
		this.courses = courses;
	}
	public Course getCourse(int id) {
		return courses.get(id);
	}
	public Courses getAllCourses() {
		return Courses.newBuilder().addAllCourse(courses.values()).build();
	}
}