package com.restapi;
import java.util.List;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;
import com.restapi.repositories.CourseRepository;
import com.restapi.grpc.CourseGRPCAutoGenerated;
import com.restapi.grpc.CourseGRPCAutoGenerated.Course;
import com.restapi.grpc.CourseGRPCAutoGenerated.Student;
import com.restapi.grpc.CourseGRPCAutoGenerated.PhoneNumber;
import com.restapi.grpc.CourseGRPCAutoGenerated.PhoneType;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.converter.protobuf.ProtobufHttpMessageConverter;
import org.springframework.web.client.RestTemplate;
@Configuration
public class AppConfig {
	@Bean
	public ProtobufHttpMessageConverter protobufHttpMessageConverter() {
		// The ProtobufHttpMessageConverter bean is used to convert responses returned by @RequestMapping annotated methods to protocol buffer messages.
		return new ProtobufHttpMessageConverter();
	}
	@Bean
	public CourseRepository createTestCourses() {
		Map<Integer, Course> courses = new HashMap<>();
		Course course1 = Course.newBuilder()
							.setId(1)
							.setName("Spring REST API")
							.addAllStudents(createTestStudents())
							.build();
		Course course2 = Course.newBuilder()
				.setId(2)
				.setName("Spring GRPC")
				.addAllStudents(new ArrayList<Student>())
				.build();
		courses.put(course1.getId(),course1);
		courses.put(course2.getId(),course2);
		return new CourseRepository(courses);
	}
	@Bean
	public RestTemplate restTemplate(ProtobufHttpMessageConverter converter) {
		return new RestTemplate(Arrays.asList(converter));
	}
	private List<Student> createTestStudents() {
		List<Student> students = new ArrayList<Student>();
		Student student1 = Student.newBuilder()
							.setId(1)
							.setFirstName("Mouse")
							.setLastName("Mickey")
							.setEmail("mickey@mouse.com")
							.addPhone(PhoneNumber.newBuilder().setNumber("+1-12345678").setType(PhoneType.MOBILE).build())
							.build();
		Student student2 = Student.newBuilder()
				.setId(1)
				.setFirstName("Donald")
				.setLastName("Duck")
				.setEmail("donald@duck.com")
				.addPhone(PhoneNumber.newBuilder().setNumber("+1-987654321").setType(PhoneType.HOME).build())
				.build();
		students.add(student1);
		students.add(student2);
		return students;
	}
}