server:
  port: 8888
  servlet:
    context-path: /restapi
spring:
  application:
    name: RestAPI
  profiles: dev    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    generate-ddl: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update      
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
jmx:
  default-domain: restapi