spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: TaigerSingapore123*
  jpa:
    hibernate:
      ddl-auto: update